### ISSUE TITLE
[FEATURE] additional notice UI

### ISSUE THREAD

**Issue by Shimsuyeon** [gsainfoteam/ziggle-fe#112]
### Description

additional notice UI

### Todos

- [ ] addtional notice UI

**Comment by Shimsuyeon** [comment]
![image](https://github.com/gsainfoteam/ziggle-fe/assets/84979352/76b3f12e-0886-47d6-b0b2-3d85f09b921e)

**Comment by 2paperstar** [comment]
suppressed by #127
