### ISSUE TITLE
[BUG] Building is extremely slow in Local Next.js env

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#122]
### Description

https://gsainfoteam.slack.com/files/U035X2ZBUTG/F064XL727MX/________________________________2023-11-07______________1.56.47.mov

Next.js 마이그레이션 뒤부터 로컬 빌드 환경이 굉장히 느립니다.

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. **맥북 에어**에서 현 master 브랜치에 있는 레포를 클론받고 env.local 파일을 루트 디렉토리에 다음과 같이 작성한다.
```
NEXT_PUBLIC_API_BASE_URL=https://api.ziggle.gistory.me/
NEXT_PUBLIC_IDP_BASE_URL=https://idp.gistory.me/
NEXT_PUBLIC_IDP_CLIENT_ID=ziggle2023
NEXT_PUBLIC_IDP_REDIRECT_URI=https://stg.ziggle.gistory.me/api/login
```
2. yarn으로 패키지를 다운받고, yarn dev로 로컬 서버를 띄운다.
3. 느리다.

### ETC

제 세컨 윈도우 컴으로 시도해보고 (제 윈도우 컴 스펙이 32GB memory, amd ryzen 7 5800h, rtx3070)
- 느리지 않다 : 성능 이슈 작용
- 느리다 : 다른 요인 작용, 요인 조사 필요
로 결론을 내리면 될 것 같습니다.
다만 이 '느리다'는 현상이 단순히 페이지 로딩이 느린것 뿐만 아니라 리렌더링 자체도 오래 걸리는 것 같아서 버튼 이벤트, 스크롤 이벤트, 라우팅 모두 느려서 개발 환경의 품질을 아주 낮추고 있습니다.
성능 이슈라도 해결이 불가피해 보입니다.

**Comment by MiRoro2** [comment]
제 세컨 컴 테스트 결과 
느립니다. 
인터넷 환경은 다운로드 230Mbps, 업로드 300Mbps입니다

**Comment by 2paperstar** [comment]
메인페이지에서 자보 이미지들을 불러올 때 next.js 측에서 image optimization을 진행하는데, 이때 사용하는 리소스로 인해서 다른쪽도 같이 느려지는 것 같습니다.
ZaboImage에서 Image태그에 unoptimization 속성을 추가해주면 잘 작동하는 것으로 보아서 이부분이 문제가 맞는 것 같아요
