### ISSUE TITLE
[FEATURE] Migration to Next.js - Write Page & International Notice-writing Support

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#123]
### Description

기존 Ziggle의 Write 페이지를 빌드한다.
뿐만 아니라 공지 작성 시 다국어 지원 기능을 추가한다.

### Todos

- [x] Migrate existing noticeWriting page (-> /[lng]/write)
- [x] Add International notice-writing support
- [x] #151

**Comment by 2paperstar** [comment]
closed by #152
