### ISSUE TITLE
[BUG] image carousel arrow disabled first rendering

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-fe#182]
### Description

#164 과 같은 이슈가 ImageCarousel 컴포넌트에도 적용 되어있습니다.

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. 이미지가 포함 되어있는 공지 상세 페이지에 접근한다.
2. 하단 부분의 ImageCarousel의 버튼이 비활성화 되어있다.

**Comment by MiRoro2** [comment]
v3 마이그레이션에서는 ImageCarousel이 쓰이지 않기 때문에 Close하겠습니다
