### ISSUE TITLE
[BUG] english additional notice field overflow

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-fe#199]
### Description

![CleanShot 2023-11-27 at 14 53 56@2x](https://github.com/gsainfoteam/ziggle-fe/assets/125528915/5b6d383e-c45b-4dba-9aed-96945157a4f4)

이거 어디까지 넘어가는거에요~

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. 영어 공지 작성
2. 필드가 넘어가서 보더가 짤림

**Comment by 2paperstar** [comment]
짤림은 사투리고 잘림

**Comment by dohyun-ko** [comment]
어디까지넘어가는거에요↗

**Comment by ParkJumyung** [comment]
이 고대의 이슈는 이제 닫아도 되겠죠?

**Comment by 2paperstar** [comment]
suppressed by new design
