### ISSUE TITLE
[BUG] korean additional notice is regarded as english notice

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-fe#200]
### Description

한국어로만 작성된 공지에 한국어 추가 공지 작성 -> 본문이 보이지 않음 -> 추가 공지 작성 필드에서는 한국어, 영어 추가 공지 필드가 동시에 뜸

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. 한국어로만 공지 작성
2. 한국어 추가 공지 추가
3. 위 버그 확인 가능

**Comment by dohyun-ko** [comment]
추가 조건: "en"일 때
