### ISSUE TITLE
[FEATURE] Build new page for Author Actions

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#241]
### Description

#240 에서 규명했던 태스크인 작성자 설정 UI 마이그레이션을 진행합니다.
디자인과 병행될 예정이며, 더 나은 UX를 위해 별도의 공지 수정 페이지를 통해 이루어지게 할 예정입니다.

### Todos

- [x] 피그마 디자인
- [ ] 마이그레이션

**Comment by ParkJumyung** [comment]
이 이슈는 다른 이슈에서 이미 해결된 이슈인가요?

**Comment by 2paperstar** [comment]
> 이 이슈는 다른 이슈에서 이미 해결된 이슈인가요?

close 해도 될 것 같습니다

resolved in #266
