### ISSUE TITLE
[FEATURE] Build Navbar for Write Notice

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#247]
### Description

공지 작성 및 수정 시 Navbar가 action을 취할 수 있도록 변형이 있는데, 이를 구현한다.
(수정 페이지 구현체가 아직은 없어서, 선행되는 작업 대로 구현하면 될 것 같다. 수정 페이지가 구현되지 않으면 굳이 터치를 안 해도 될 듯)

### Todos

- [x] Build Navbar for Write Notice

**Comment by ParkJumyung** [comment]
이 이슈는 다른 이슈 해결하면서 이미 구현된거죠?
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/c6edefd9-5813-4fe0-9cfe-ea53cfc95f55)

**Comment by MiRoro2** [comment]
아 내가 했었구나
뭐지
