### ISSUE TITLE
[FEATURE] Mypage Responsive + Empty content Design

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#25]
### 마이페이지가 작은 view width에서도 제대로 보일 수 있도록 반응형 추가
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/32bf9157-ace7-4d1d-aa84-aee33f562cbd)

### 테이블에 아무 데이터도 없을 때 아래같은 고양이 사진이 나타날 수 있도록 수정
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/6165f3f5-4190-468f-9b59-9c9a666a5ea1)

고양이 asset은 Mypage 디렉토리에 LazyCat.tsx로 넣어놓음

### Todos

- [x] Add Responsive View
- [x] Add Empty Content Design (LazyCat)

**BugFix**
- [x] p tag 중첩

**Comment by Shimsuyeon** [comment]
p tag, 반응형은 수정했고,
빈 article은 lazycat 삽입하는 작업해놨는데, 표가 제목/날짜로 나뉘어 있고, 고양이를 표 제목쪽에 넣었더니 가운데 정렬을 해도 정확히 가운데가 아니라서 다시 수정하겠습니다.

**Comment by Shimsuyeon** [comment]
table -> div로 바꾸고 고양이 가운데 정렬했습니다
proptype validation 에러도 해결했습니다.
제목 길면 짜르고 ...으로 생략했습니다.
