### ISSUE TITLE
[BUG] misc bugs

### ISSUE THREAD

**Issue by ParkJumyung** [gsainfoteam/ziggle-fe#260]
### Description

Newly discovered not so miscellaneous bugs
---
- [x] Near deadline category page 502 error on next page
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/693f11e1-d744-4a9a-bd13-a55bcaa2641e)
deadline category page->scroll to bottom->click next page button in pagination->502 error

- [x] #294
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/b00d681d-07d3-4820-a7ff-0fa9bc7c6eca)
category page(recruit, events, general, academic) -> toggle "Sort by deadline"->nothing

- [x] #296
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/065e373e-d1af-4b31-b617-d5e55e355f87)
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/db927abb-ccb9-42a0-8fd8-a7066ae3695d)
any zabo or notice detail page -> click reactions -> nothing happens('login required' toast should be shown)

- [x] #304
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/d8b692c6-6297-438e-8fb2-911b5c7e17c3)
write page(to write notice) -> shows description for editing notice

- [x] #299
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/1cfb2fbd-80f3-4a75-89db-974bdbfeead3)
user can access write page withoug logging in. If user clicks submit without logging in, it crashes with unhandled 401 error

- [x] #298
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/d3e3ac81-0e72-402e-b1bf-ab29972254ce)
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/51580e75-5087-4952-b19f-252d08491f12)
write page -> title input field

- [x] #303
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/898223e6-a8df-41d4-ae21-17dfaf90963d)

- [x] #300
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/200be299-8e51-41be-9892-ecc47dd7ad88)

---

- [x] #286
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/d077efd0-25f1-4489-a0d5-9b362b9b547e)
write page>attatch photo>dark mode icon styling issue in add photo icon

- [x] #282
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/89ba4a4a-7d75-42f6-98bb-75df018514c5)
write page>submit>500 error>keep showing progress modal rather than showing error message

- [x] #267
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/221b37b2-7f1e-4faa-89db-b90108d4535e)
any page with zabo(notice detail, main, search, ...)>click tag>directs to deprecated /section/tagname

- [x] #265
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/d43ae21c-3e29-479f-a5e2-26804fca8a21)
login>click reaction at zabo or notice detail page>rejected and login required toast shown

- [x] #278
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/c3351d35-7b0b-44b9-8408-a1d4f73244eb)
search bar>enter query>click search icon>nothing>click again>works

- [x] #284
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/084a1945-08b1-4d1e-9ab2-a68eee508b14)
sidebar>click groups>directs to /categoty/groups(which shows same content as home as default)

- [x] 7. 500 error on logout
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/5978b08f-5a91-452e-98f7-9edd856fb083)
login>mypage>logout>500 error

- [x] 8. Author actions does not appear even the user is the author of the notice
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/faeedddc-4205-4903-a809-9969739e1a68)
logged in>notice(that I wrote) detail page>Author actions does not appear

- [x] #264
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/fbf8e094-c5b0-40c0-9e75-46e9b0190df2)
write page>write something>submit>navigate to other pages>write page>temporarily saved notice modal appears even though the notice is already successfuly submitted

- [x] #288
(without cache) click left top logo > navigate to /home > navigate to /home?page=0 > this occurs blinking (loading)

**Comment by 2paperstar** [comment]
all resolved
