### ISSUE TITLE
Show error page when error occurs

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-fe#282]
- alert
	- write notice
	- delete notice
	- write additional notice
	- write foreign notice
- toast
	- add reaction
	- delete reaction

**Comment by ParkJumyung** [comment]
공지를 submit할 때 api에 POST가 실패했음에도 불구하고 에러를 보여주는 대신 계속 공지를 작성하는 중이라는 모달이 떠있는 버그가 있었습니다. 
전반적으로 api에 요청이 실패했을때 try catch에서 catch로 넘어가지 않는 문제가 있는 것 같습니다.
