### ISSUE TITLE
[BUG] more ui bugs

### ISSUE THREAD

**Issue by ParkJumyung** [gsainfoteam/ziggle-fe#321]
### Description

- [x] write page tag suggestion dark mode issue
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/7e4f76c3-b712-4bf5-84f3-02549ce06c1a)
write page > tag input > write something > tag suggestions
- [x] deadline in notice detail page dark mode issue
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/1994591c-a525-4e5f-b0a6-c15fb2436e2c)
- [ ] search bar overflow on narrow screen
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/5a0c4d50-2420-47be-9677-25b6daf55fa6)
- [x] category page text sizing issue on narrow screen
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/4d60747f-7831-415c-9dd2-aca5bf1bd399)
- [x] install app modal pops up whenever home refreshes
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/e2432bdb-38ef-4959-b48e-10635240cffd)
- [ ] returning to home sometimes does not show any content
![image](https://github.com/gsainfoteam/ziggle-fe/assets/126857540/63c38d76-ada2-4394-b634-cbbd18b749ef)
return to home by clicking ziggle or 'go back' at write page > sometimes home page doesn't show any content (hard to consistently reproduce)
- [ ] English Additional notice shows up when even the English notice is not wrote
![image](https://github.com/gsainfoteam/ziggle-fe/assets/57053429/aa59c8c8-b063-4ef7-8773-c325bf65570a)

**Comment by MiRoro2** [comment]
>  English Additional notice shows up when even the English notice is not wrote
@ParkJumyung

이것의 경우, 추가공지의 경우 차라리 탭뷰와 별개의 UI로 가져가는 게 나아보이는데 어떻게 생각하시나요
