### ISSUE TITLE
[BUG] bug in notice edit

### ISSUE THREAD

**Issue by ParkJumyung** [gsainfoteam/ziggle-fe#323]
### Description

cannot access notice edit page due to unhandled runtime error

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. login
2. My Notices
3. click one notice
4. click edit/add english notice button

**Comment by 2paperstar** [comment]
api가 잘못 향하고 있는 것 같아요
#319 에서 같이 리졸브하겠습니다
