### ISSUE TITLE
[BUG] All the category sections are returning same notices

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#336]
### Description

현재 웹의 모든 카테고리 섹션이 같은 공지 목록을 반환하고 있습니다. api param을 잘못 구성했을 가능성이 있습니다.

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. 지글 홈페이지에 들어간다.
2. 모집/행사/일반/학사 섹션에 들어간다.
3. 모두 같은 공지 목록이 반환된다.

**Comment by dohyun-ko** [comment]
백엔 업데이트로 이슈 해결됨
