### ISSUE TITLE
[BUG] should restrict the image height when it is too long, in Zabo component

### ISSUE THREAD

**Issue by crown-3** [gsainfoteam/ziggle-fe#337]
### Description

- 메인에 나오는 자보 컴포넌트의 이미지 높이(height)가 너무 길면 어느 정도 선에서 잘라줘야 하는데, 이게 안 되어서 하단 영상과 같이 이미지가 엿가락처럼 늘어지는 현상이 발생하고 있습니다.

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. 지글 홈페이지 메인에 들어간다.

https://github.com/gsainfoteam/ziggle-fe/assets/57053429/d3d5d35d-156f-42ae-a41a-d66176c6f1a9

**Comment by 2paperstar** [comment]
엿가락,,, ㅎㅋㅋㅋ
