### ISSUE TITLE
[BUG] fix miscellaneous dark mode related bugs

### ISSUE THREAD

**Issue by ParkJumyung** [gsainfoteam/ziggle-fe#364]
### Description

- [x] ziggle text logo on nav bar in darkmode

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. nav bar in darkmode

**Comment by enc2586** [comment]
어째서인지 이 커밋에서 같이 해결됐네요. 럭키비키~
