### ISSUE TITLE
[BUG] can't see any page without authentication

### ISSUE THREAD

**Issue by 2paperstar** [gsainfoteam/ziggle-fe#51]
### Description

로그인 없이는 다른 페이지로 이동이 불가능합니다

### How to reproduce (재현 불가능 한 경우 '재현 불가능'이라고 적어주세요)

1. logout if logged in.
2. navigate to any page not root(/)

**Comment by dohyun-ko** [comment]
Solved: https://github.com/gsainfoteam/ziggle-fe/pull/53
