### ISSUE TITLE
[FEATURE] 학사공지 긁어와서 보여주기

### ISSUE THREAD

**Issue by MiRoro2** [gsainfoteam/ziggle-fe#63]
### Description

Mock으로만 되어 있는 HomePage의 학사공지(AcademicNotices)에 API를 붙인다.

### Todos

- [ ] 학사공지 긁어오는 API 만들기
- [ ] API 붙이기

**Comment by dohyun-ko** [comment]
학사공지 수동 업로드로 변경했습니다
